FROM python:3.12-bookworm

# Install Scientific Python packages with PIP
RUN pip install numpy scipy matplotlib pandas sympy statsmodels
# Install Jupyter packages
RUN pip install jupyterlab ipykernel