#!/bin/bash
# 02-config.sh - Generate server.properties from environment variables

set -euo pipefail

source /opt/container/entrypoint.d/scripts/utils/logging.sh
source /opt/container/entrypoint.d/scripts/utils/helpers.sh

CONFIG_FILE="/opt/kafka/config/server.properties"

main() {
    log_script_start "02-config.sh"

    generate_config

    log_script_end "02-config.sh"
}

generate_config() {
    log_info "Generating Kafka configuration: $CONFIG_FILE"

    cat > "$CONFIG_FILE" <<EOF
# Kafka server configuration for KRaft mode
# Generated by container entrypoint on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Process roles
process.roles=${KAFKA_PROCESS_ROLES:-broker,controller}
node.id=${KAFKA_NODE_ID:-1}

# Controller configuration
controller.quorum.voters=${KAFKA_CONTROLLER_QUORUM_VOTERS:-1@localhost:9093}
controller.listener.names=${KAFKA_CONTROLLER_LISTENER_NAMES:-CONTROLLER}

# Listeners
listeners=${KAFKA_LISTENERS:-PLAINTEXT://:9092,CONTROLLER://:9093}
inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME:-PLAINTEXT}
advertised.listeners=${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://localhost:9092}
listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:-CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL}

# Network and I/O threads
num.network.threads=${KAFKA_NUM_NETWORK_THREADS:-3}
num.io.threads=${KAFKA_NUM_IO_THREADS:-8}

# Socket configuration
socket.send.buffer.bytes=${KAFKA_SOCKET_SEND_BUFFER_BYTES:-102400}
socket.receive.buffer.bytes=${KAFKA_SOCKET_RECEIVE_BUFFER_BYTES:-102400}
socket.request.max.bytes=${KAFKA_SOCKET_REQUEST_MAX_BYTES:-104857600}

# Log configuration
num.partitions=${KAFKA_NUM_PARTITIONS:-1}
num.recovery.threads.per.data.dir=${KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR:-1}
log.dirs=${KAFKA_LOG_DIRS:-/opt/kafka/data}
offsets.topic.replication.factor=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-1}
transaction.state.log.replication.factor=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:-1}
transaction.state.log.min.isr=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:-1}
log.retention.hours=${KAFKA_LOG_RETENTION_HOURS:-168}
log.segment.bytes=${KAFKA_LOG_SEGMENT_BYTES:-1073741824}
log.retention.check.interval.ms=${KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS:-300000}

# Group configuration
group.initial.rebalance.delay.ms=${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS:-0}

# Auto topic creation
auto.create.topics.enable=${KAFKA_AUTO_CREATE_TOPICS_ENABLE:-true}

# Message size limits
message.max.bytes=${KAFKA_MESSAGE_MAX_BYTES:-1048588}
replica.fetch.max.bytes=${KAFKA_REPLICA_FETCH_MAX_BYTES:-1048576}

# Connection limits
max.connections.per.ip=${KAFKA_MAX_CONNECTIONS_PER_IP:-2147483647}
max.connection.creation.rate=${KAFKA_MAX_CONNECTION_CREATION_RATE:-2147483647}

# Topic deletion
delete.topic.enable=${KAFKA_DELETE_TOPIC_ENABLE:-true}

# SASL Configuration
sasl.enabled.mechanisms=${KAFKA_SASL_ENABLED_MECHANISMS:-PLAIN}
sasl.mechanism.inter.broker.protocol=${KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL:-PLAIN}
EOF

    # Apply any additional KAFKA_CONFIG_* environment variables
    apply_custom_config

    log_info "Kafka configuration generated successfully"
}

apply_custom_config() {
    log_debug "Applying custom KAFKA_CONFIG_* environment variables"

    while IFS='=' read -r var_name var_value; do
        if [[ "$var_name" =~ ^KAFKA_CONFIG_ ]]; then
            local key_name
            key_name=$(echo "${var_name#KAFKA_CONFIG_}" | tr '[:upper:]' '[:lower:]' | tr '_' '.')
            log_debug "Setting custom config: $key_name = $var_value"

            if grep -q "^${key_name}=" "$CONFIG_FILE"; then
                sed -i "s|^${key_name}=.*|${key_name}=${var_value}|g" "$CONFIG_FILE"
            else
                echo "${key_name}=${var_value}" >> "$CONFIG_FILE"
            fi
        fi
    done < <(env)
}

main "$@"
