scope: postgres-default
namespace: /default/
name: postgresql-1

restapi:
  listen: 0.0.0.0:8008
  connect_address: localhost:8008

etcd:
  hosts:
    - localhost:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    initdb:
      - encoding: UTF8
      - data-checksums
    postgresql:
      parameters:
        max_connections: 500

postgresql:
  listen: 0.0.0.0:5432
  connect_address: localhost:5432
  # Proxy address is used by HAProxy to connect to PostgreSQL
  # It should be the same as `connect_address` if HAProxy is running on the
  # same host as Patroni, or it should be the address of the HAProxy instance
  # if it's running on a different host.
  proxy_address: localhost:5432
  data_dir: /bitnami/postgresql/data
  bin_dir: /opt/bitnami/postgresql/bin
  pgpass: /opt/bitnami/postgresql/conf/.pgpass
  config_dir: /opt/bitnami/postgresql/conf
  authentication:
    superuser:
      username: postgres
      password: 
    replication:
      username: replicator
      password: 
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host all all ::0/0 md5
    - local all all trust
    - host replication replicator 0.0.0.0/0 md5
    - host replication replicator ::0/0 md5
  parameters:
    shared_preload_libraries: "citus,pg_stat_statements,pgaudit"

watchdog:
  mode: off