#!/bin/bash
# 02-config.sh - Generate FreeRADIUS configuration files

set -euo pipefail

source /opt/container/entrypoint.d/scripts/utils/logging.sh
source /opt/container/entrypoint.d/scripts/utils/validation.sh
source /opt/container/entrypoint.d/scripts/utils/security.sh

main() {
    log_script_start "02-config.sh"
    
    if ! validate_environment; then
        log_error "Environment validation failed"
        return 1
    fi
    
    check_default_secret
    
    local radius_etc="/usr/local/freeradius/etc/raddb"
    local radius_log="/usr/local/freeradius/log"
    
    use_default_configs "$radius_etc"
    
    log_script_end "02-config.sh"
}

use_default_configs() {
    local etc_dir="$1"
    
    log_info "Using default FreeRADIUS configuration"
    
    if [[ -f "$etc_dir/radiusd.conf.original" ]]; then
        cp "$etc_dir/radiusd.conf.original" "$etc_dir/radiusd.conf"
    fi
    
    if [[ -f "$etc_dir/clients.conf.original" ]]; then
        cp "$etc_dir/clients.conf.original" "$etc_dir/clients.conf"
    fi
    
    if [[ -f "$etc_dir/users.original" ]]; then
        cp "$etc_dir/users.original" "$etc_dir/users"
    fi
    
    log_info "Default configs restored"
    
    update_client_secret "$etc_dir/clients.conf"
}

update_client_secret() {
    local clients_file="$1"
    local default_secret="${RADIUS_DEFAULT_SECRET:-secret}"
    
    log_info "Updating client secret to: $default_secret"
    
    sed -i "s/secret[[:space:]]*=.*/secret = $default_secret/" "$clients_file"
    sed -i "s/secret[[:space:]]*:=.*/secret := $default_secret/" "$clients_file"
    
    log_info "Client secret updated"
}

backup_original_configs() {
    local etc_dir="$1"
    log_info "Backing up original configuration files"
    
    local config_files=("radiusd.conf" "clients.conf" "users")
    
    for file in "${config_files[@]}"; do
        local source_file="$etc_dir/$file"
        local backup_file="$etc_dir/$file.original"
        
        if [[ -f "$source_file" ]] && [[ ! -f "$backup_file" ]]; then
            cp "$source_file" "$backup_file"
            log_debug "Backed up $file to $file.original"
        fi
    done
}

copy_user_configs() {
    local etc_dir="$1"
    local config_dir="/usr/local/freeradius/config"
    
    if [[ ! -d "$config_dir" ]]; then
        log_debug "Config directory does not exist, skipping user config copy"
        return 0
    fi
    
    log_info "Copying user-provided configuration files"
    
    local config_files=("radiusd.conf" "clients.conf" "users" "proxy.conf")
    
    for file in "${config_files[@]}"; do
        local source_file="$config_dir/$file"
        local dest_file="$etc_dir/$file"
        
        if [[ -f "$source_file" ]]; then
            cp "$source_file" "$dest_file"
            set_secure_permissions "$dest_file"
            log_info "Copied user config: $file"
        else
            log_debug "User config not provided: $file"
        fi
    done
}

generate_radiusd_conf() {
    local config_file="$1"
    
    log_debug "Generating radiusd.conf: $config_file"
    
    local listen_addr="${RADIUS_LISTEN_ADDR:-*}"
    local auth_port="${RADIUS_AUTH_PORT:-1812}"
    local acct_port="${RADIUS_ACCT_PORT:-1813}"
    local status_port="${RADIUS_STATUS_PORT:-}"
    local timeout="${RADIUS_TIMEOUT:-30}"
    local max_request="${RADIUS_MAX_REQUEST:-4096}"
    local max_attributes="${RADIUS_MAX_ATTRIBUTES:-200}"
    local log_level="${RADIUS_LOG_LEVEL:-info}"
    local timezone="${FREERADIUS_TIMEZONE:-UTC}"
    
    cat > "$config_file" << EOF
# FreeRADIUS configuration generated by container
prefix = /usr/local/freeradius
exec_prefix = \${prefix}
sysconfdir = \${prefix}/etc
localstatedir = \${prefix}
sbindir = \${exec_prefix}/sbin
logdir = /usr/local/freeradius/log
raddbdir = /usr/local/freeradius/etc/raddb
radacctdir = \${logdir}/radacct
name = radiusd
confdir = \${raddbdir}
modconfdir = \${confdir}/mods-config
certdir = \${confdir}/certs
cadir = \${confdir}/certs
run_dir = \${localstatedir}/run/\${name}
db_dir = \${localstatedir}/lib/\${name}
libdir = \${exec_prefix}/lib
pidfile = \${run_dir}/\${name}.pid

request {
    max = ${max_request}
    timeout = ${timeout}
    reuse {
        min = 10
        cleanup_interval = 30s
    }
}

hostname_lookups = no

log {
    destination = files
    colourise = yes
    file = \${logdir}/radius.log
    syslog_facility = daemon
}

log_auth = yes
log_auth_badpass = yes
log_auth_goodpass = yes

security {
    max_attributes = ${max_attributes}
    allow_vulnerable_openssl = no
}

\$INCLUDE clients.conf
\$INCLUDE users

thread pool {
    num_workers = 1
}

listen {
    type = auth
    ipaddr = ${listen_addr}
    port = ${auth_port}
}

listen {
    type = acct
    ipaddr = ${listen_addr}
    port = ${acct_port}
}
EOF
    
    if [[ -n "$status_port" ]]; then
        cat >> "$config_file" << EOF

listen {
    type = status
    ipaddr = ${listen_addr}
    port = ${status_port}
}
EOF
    fi
    
    cat >> "$config_file" << EOF

\$INCLUDE mods-enabled/
EOF
    
    set_secure_permissions "$config_file"
    log_debug "Generated radiusd.conf"
}

generate_clients_conf() {
    local config_file="$1"
    
    log_debug "Generating clients.conf: $config_file"
    
    local default_secret="${RADIUS_DEFAULT_SECRET:-secret}"
    
    cat > "$config_file" << EOF
# FreeRADIUS clients configuration generated by container
# Clients configuration

client localhost {
    ipaddr = 127.0.0.1
    secret = ${default_secret}
    require_message_authenticator = no
}

client localhost_ipv6 {
    ipv6addr = ::1
    secret = ${default_secret}
    require_message_authenticator = no
}
EOF
    
    if [[ -n "${RADIUS_CLIENT_NETWORK:-}" ]]; then
        local network="${RADIUS_CLIENT_NETWORK%%:*}"
        local secret="${RADIUS_CLIENT_NETWORK#*:}"
        [[ "$secret" == "$network" ]] && secret="$default_secret"
        
        cat >> "$config_file" << EOF

client ${network} {
    ipaddr = ${network}
    secret = ${secret}
}
EOF
    fi
    
    if [[ -n "${RADIUS_CLIENTS:-}" ]]; then
        IFS=',' read -ra CLIENTS <<< "$RADIUS_CLIENTS"
        for client in "${CLIENTS[@]}"; do
            client="$(echo "$client" | tr -d '[:space:]')"
            if [[ "$client" =~ ^([^:]+):([^:]+):(.+)$ ]]; then
                local name="${BASH_REMATCH[1]}"
                local ip="${BASH_REMATCH[2]}"
                local secret="${BASH_REMATCH[3]}"
                
                cat >> "$config_file" << EOF

client ${name} {
    ipaddr = ${ip}
    secret = ${secret}
}
EOF
            elif [[ "$client" =~ ^([^:]+):(.+)$ ]]; then
                local ip="${BASH_REMATCH[1]}"
                local secret="${BASH_REMATCH[2]}"
                
                cat >> "$config_file" << EOF

client ${ip} {
    ipaddr = ${ip}
    secret = ${secret}
}
EOF
            fi
        done
    fi
    
    set_secure_permissions "$config_file"
    log_debug "Generated clients.conf"
}

generate_sql_config() {
    local config_file="$1"
    local config_dir="$(dirname "$config_file")"
    local enabled_dir="$config_dir/../mods-enabled"
    
    log_info "Generating SQL module configuration"
    
    local db_type="${DB_TYPE:-mysql}"
    local db_host="${DB_HOST:-localhost}"
    local db_port="${DB_PORT:-3306}"
    local db_name="${DB_NAME:-radius}"
    local db_user="${DB_USER:-radius}"
    local db_pass="${DB_PASS:-}"
    local db_dialect="${DB_DIALECT:-$db_type}"
    
    cat > "$config_file" << EOF
# SQL module configuration
sql {
    driver = "rlm_sql_${db_type}"
    dialect = "${db_dialect}"

    server = "${db_host}"
    port = ${db_port}
    login = "${db_user}"
    password = "${db_pass}"

    radius_db = "${db_name}"

    read_groups = yes
    read_profiles = yes
    read_clients = yes

    delete_stale_sessions = yes

    pool {
        start = 5
        min = 3
        max = ${DB_POOL_MAX:-20}
        spare = 3
        uses = 0
        retry_delay = 30
        lifetime = 0
        idle_timeout = 60
    }

    client_table = "nas"
    accounting_table = "radacct"
    postauth_table = "radpostauth"
    authcheck_table = "radcheck"
    authreply_table = "radreply"
    groupmembership_table = "radusergroup"
    usergroup_table = "radusergroup"
    simultaneous_use_check = yes
    uncomment = yes
}
EOF
    
    set_secure_permissions "$config_file"
    
    if [[ ! -e "$enabled_dir/sql" ]]; then
        ln -sf "$config_file" "$enabled_dir/sql"
        log_info "Enabled SQL module"
    fi
}

generate_ldap_config() {
    local config_file="$1"
    local config_dir="$(dirname "$config_file")"
    local enabled_dir="$config_dir/../mods-enabled"
    
    log_info "Generating LDAP module configuration"
    
    local ldap_server="${LDAP_SERVER:-}"
    local ldap_port="${LDAP_PORT:-389}"
    local ldap_identity="${LDAP_IDENTITY:-}"
    local ldap_password="${LDAP_PASSWORD:-}"
    local ldap_base_dn="${LDAP_BASE_DN:-}"
    
    cat > "$config_file" << EOF
# LDAP module configuration
ldap {
    server = "${ldap_server}"
    port = ${ldap_port}
    identity = "${ldap_identity}"
    password = "${ldap_password}"

    base_dn = "${ldap_base_dn}"

    update {
        control:Password-With-NAI += userPassword
    }

    user {
        base_dn = "\${base_dn}"
        filter = "(uid=%{%{Stripped-User-Name}:-%{User-Name}})"
    }

    account {
        expire_date = "accountExpire"
        mod_date = "modifyTimestamp"
    }

    group {
        base_dn = "\${base_dn}"
        filter = '(objectClass=posixGroup)'
        name_attr = cn
        membership_attribute = memberUid
    }
}
EOF
    
    set_secure_permissions "$config_file"
    
    if [[ ! -e "$enabled_dir/ldap" ]]; then
        ln -sf "$config_file" "$enabled_dir/ldap"
        log_info "Enabled LDAP module"
    fi
}

main "$@"
