// runtime.js — runtime/startup: supervise the database + sidecar process tree
// in a single chain. ezx stays PID 1 and supervises the postgres/patroni root
// and every needParentReady child (stanza/userlist/repl-user init one-shots,
// pgbouncer, sshd, scheduled backups, Patroni role-check) concurrently,
// forwarding signals, reaping zombies, and draining on SIGTERM.
const { env, fs, chain, scheduler } = require("ezx");
const {
	PGDATA,
	PGRUN,
	PG_USER,
	PG_GROUP,
	PG_PORT,
	PG_PASS,
	PATRONI_ENABLE,
	PGBOUNCER_ENABLE,
	PGBACKREST_ENABLE,
	PATRONI_CONF,
	PGBOUNCER_INI,
	PGBOUNCER_USERLIST,
	REPL_ROLE,
	REPL_USER,
	REPL_PASSWORD,
	HA_MODE,
	STANZA,
	TIMEOUT,
	PG_READY_MAX_ATTEMPTS,
} = require("./env");
const { postgresFiles } = require("./config");
const { backupNodes, registerBackupRoutes } = require("./backup");
const { roleCheckUrl } = require("./patroni");

function quoteArg(a) {
	return "'" + String(a).replace(/'/g, "'\\''") + "'";
}

// oneShot — a needParentReady child that runs a command to completion then
// exits (stanza-create, userlist generation, replication-user creation).
function oneShot(name, cmd, opts) {
	const base = {
		binaryPath: "/bin/sh",
		arguments: ["-c", cmd],
		user: PG_USER,
		group: PG_GROUP,
	};
	return Object.assign(
		{ name, needParentReady: true, process: base },
		opts || {},
		{ process: Object.assign(base, (opts && opts.process) || {}) },
	);
}

// userlist-init — query pg_shadow for the postgres password hash and write
// pgbouncer userlist.txt (bash startup.sh:285-302). Uses shell redirection
// because ezx exposes no stdout capture.
function userlistInit() {
	if (!PGBOUNCER_ENABLE) return null;
	let cmd;
	if (PG_PASS) {
		cmd =
			"PGPASSWORD=" +
			quoteArg(PG_PASS) +
			" psql -v ON_ERROR_STOP=1 -tA -h " +
			quoteArg(PGRUN) +
			" -d postgres -U " +
			quoteArg(env.get("POSTGRES_USER", "postgres")) +
			" -c " +
			quoteArg("SELECT passwd FROM pg_shadow WHERE usename = '" + (env.get("POSTGRES_USER", "postgres") || "").replace(/'/g, "''") + "';") +
			" | sed 's/^/\"" + (env.get("POSTGRES_USER", "postgres") || "").replace(/"/g, '\\"') + "\" \"/; s/$/\"/'" +
			" > " + PGBOUNCER_USERLIST;
	} else {
		cmd = 'echo "' + (env.get("POSTGRES_USER", "postgres") || "") + '" "" > ' + PGBOUNCER_USERLIST;
	}
	cmd += " && chown " + PG_USER + ":" + PG_GROUP + " " + PGBOUNCER_USERLIST + " && chmod 600 " + PGBOUNCER_USERLIST;
	return oneShot("pgbouncer-userlist", cmd);
}

// stanza-init — create/upgrade the pgBackRest stanza once postgres is ready
// (bash startup.sh:initialize_pgbackrest_stanza + cluster.sh modes).
function stanzaInit() {
	if (!PGBACKREST_ENABLE) return null;
	const cmd =
		"if ! pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
		quoteArg(STANZA) +
		" stanza-create; then pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
		quoteArg(STANZA) +
		" stanza-upgrade; fi && pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
		quoteArg(STANZA) +
		" check";
	return oneShot("pgbackrest-stanza-init", cmd, {
		process: { filterEnvPattern: ["^PGBACKREST_"] },
	});
}

// repl-user — create the replication user for native-HA primary (bash
// startup.sh:create_replication_user).
function replUser() {
	if (HA_MODE !== "native" || REPL_ROLE !== "primary" || !REPL_USER) return null;
	if (!REPL_PASSWORD) throw new Error("REPLICATION_PASSWORD required for native-HA primary");
	const cmd =
		"PGPASSWORD=" +
		quoteArg(REPL_PASSWORD) +
		" psql -h 127.0.0.1 -p " +
		PG_PORT +
		" -U " +
		quoteArg(env.get("POSTGRES_USER", "postgres")) +
		" -d postgres -c " +
		quoteArg(
			"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '" + (REPL_USER || "").replace(/'/g, "''") + "') THEN CREATE ROLE " + REPL_USER + " REPLICATION LOGIN PASSWORD '" + REPL_PASSWORD.replace(/'/g, "''") + "'; END IF; END $$;",
		);
	return oneShot("replication-user", cmd);
}

// pgbouncerNode — supervised long-running pgbouncer sidecar (restart always).
// The pgbouncer.ini is generated by the postgresFiles FileProvision during
// chain.run (gated on PGBOUNCER_ENABLE), so no existence check here — it runs
// before provisioning and would fail spuriously. Runs pgbouncer in foreground
// (no -d): daemon mode forks and the parent exits 0 immediately, which would
// make ezx restart-loop on the still-held socket.
function pgbouncerNode() {
	if (!PGBOUNCER_ENABLE) return null;
	return {
		name: "pgbouncer",
		needParentReady: true,
		process: {
			binaryPath: "pgbouncer",
			arguments: [PGBOUNCER_INI],
			user: PG_USER,
			group: PG_GROUP,
		},
		restart: { mode: "always", backoff: 2e9 },
		forwardSignals: ["SIGTERM", "SIGINT", "SIGHUP"],
	};
}

// sshdNode — supervised long-running sshd sidecar on the primary (restart
// always). Gated on REPL_ROLE because this is evaluated at tree-build time,
// before postgres is up; native replicas are never primary. Runs sshd with -D
// (don't daemonize): without it sshd forks into the background and the parent
// exits 0 immediately, making ezx restart-loop on the held port 22.
function sshdNode() {
	if (REPL_ROLE === "replica") return null;
	if (!fs.exists("/usr/sbin/sshd")) return null;
	return {
		name: "sshd",
		needParentReady: true,
		process: { binaryPath: "/usr/sbin/sshd", arguments: ["-D"] },
		restart: { mode: "always", backoff: 2e9 },
		forwardSignals: ["SIGTERM", "SIGINT", "SIGHUP"],
	};
}

function startSleep() {
	chain.run({
		roots: [
			{
				name: "sleep",
				process: {
					binaryPath: "/bin/sh",
					arguments: ["-c", "while true; do sleep 3600; done"],
				},
				restart: { mode: "always", backoff: 1000 * 1e6 },
			},
		],
	});
}

// roleCheckNode — a scheduled curl child that POSTs to the in-process Patroni
// role-check api route every minute, so a promote/demote regenerates
// pgbackrest.conf without any external callback executable.
function roleCheckNode() {
	if (!PATRONI_ENABLE || !PGBACKREST_ENABLE || !env.get("EZX_HEALTH_ADDR")) return null;
	return {
		name: "patroni-role-check",
		needParentReady: true,
		process: {
			binaryPath: "curl",
			arguments: ["-sf", "-X", "POST", roleCheckUrl()],
		},
		scheduler: scheduler.build({
			schedule: {
				expression: env.get("PATRONI_ROLE_CHECK_CRON", "*/1 * * * *"),
				timezone: env.get("PGBACKREST_AUTO_TIMEZONE", "UTC"),
			},
			initialDelay: 30e9,
			minInterval: 60e9,
		}),
	};
}

function startDatabase() {
	const mainProcess = PATRONI_ENABLE
		? {
				binaryPath: "patroni",
				arguments: [PATRONI_CONF],
				user: PG_USER,
				group: PG_GROUP,
			}
		: {
				binaryPath: env.get("POSTGRES_BIN", "postgres"),
				arguments: ["-D", PGDATA],
				user: PG_USER,
				group: PG_GROUP,
			};

	const children = [
		stanzaInit(),
		replUser(),
		userlistInit(),
		pgbouncerNode(),
		sshdNode(),
		roleCheckNode(),
	]
		.concat(backupNodes())
		.filter(Boolean);

	const node = {
		name: PATRONI_ENABLE ? "patroni" : "postgres",
		process: mainProcess,
		files: postgresFiles,
		forwardSignals: ["SIGTERM", "SIGINT", "SIGHUP", "SIGUSR1", "SIGUSR2"],
		shutdown: { timeout: TIMEOUT * 1e9, forceKill: true },
		children,
	};

	// Readiness probe gating needParentReady children (postgres must accept
	// connections before stanza-init/userlist/pgbouncer/sshd start). Mirrors
	// the bash wait_for_postgresql_ready loop. Set unconditionally — node.health
	// (the /readyz HTTP surface) is only wired when EZX_HEALTH_ADDR is set.
	node.readiness = {
		type: "exec",
		exec: ["pg_isready", "-h", PGRUN, "-p", PG_PORT, "-U", PG_USER],
		interval: 1e9,
		timeout: 5e9,
		maxAttempts: PG_READY_MAX_ATTEMPTS,
	};

	const healthAddr = env.get("EZX_HEALTH_ADDR");
	if (healthAddr) {
		node.health = { readyProbe: node.readiness };
		registerBackupRoutes();
	}

	chain.run({ roots: [node] });
}

module.exports = {
	startPgbouncer: pgbouncerNode,
	startSshd: sshdNode,
	startSleep,
	startDatabase,
};