name: Build and Publish Containers

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      container: ${{ steps.extract.outputs.container }}
      revision: ${{ steps.extract.outputs.revision }}
      matrix: ${{ steps.versions.outputs.matrix }}
      context: ${{ steps.versions.outputs.context }}
    steps:
      - name: Extract container and revision
        id: extract
        run: |
          TAG=${{ github.event.release.tag_name }}
          CONTAINER=${TAG%%-*}
          REVISION=${TAG#*-}
          echo "container=$CONTAINER" >> $GITHUB_OUTPUT
          echo "revision=$REVISION" >> $GITHUB_OUTPUT

      - name: Set matrix and context
        id: versions
        run: |
          CONTAINER=${{ steps.extract.outputs.container }}
          if [ "$CONTAINER" = "postgresql" ]; then
            MATRIX='[
              {"version": "13.5", "build_args": "POSTGRESQL_VERSION=13.5\nCITUS_VERSION=11.3.1\nPATRONI_VERSION=v3.0.2"},
              {"version": "14", "build_args": "POSTGRESQL_VERSION=14\nCITUS_VERSION=12.1.0\nPATRONI_VERSION=v3.1.0"},
              {"version": "18", "build_args": "POSTGRESQL_VERSION=18\nCITUS_VERSION=13.0.0\nPATRONI_VERSION=v4.0.0"}
            ]'
            CONTEXT="docker/postgresql"
          elif [ "$CONTAINER" = "wordpress" ]; then
            MATRIX='[{"version": "latest", "build_args": ""}]'
            CONTEXT="docker/wordpress/apache"
          else
            MATRIX='[{"version": "latest", "build_args": ""}]'
            CONTEXT="docker/$CONTAINER"
          fi
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

  build:
    needs: setup
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ needs.setup.outputs.context }}
          push: true
          build-args: ${{ matrix.build_args }}
          tags: ghcr.io/${{ github.repository_owner }}/containers/${{ needs.setup.outputs.container }}:${{ matrix.version }}-${{ needs.setup.outputs.revision }}
          cache-from: type=gha
          cache-to: type=gha,mode=max