name: Build and Publish Containers

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      container: ${{ steps.extract.outputs.container }}
      revision: ${{ steps.extract.outputs.revision }}
      matrix: ${{ steps.versions.outputs.matrix }}
      context: ${{ steps.versions.outputs.context }}
    steps:
      - name: Extract container and revision
        id: extract
        run: |
          TAG=${{ github.event.release.tag_name }}
          CONTAINER=${TAG%%-*}
          REVISION=${TAG#*-}
          echo "container=$CONTAINER" >> $GITHUB_OUTPUT
          echo "revision=$REVISION" >> $GITHUB_OUTPUT

      - name: Set matrix and context
        id: versions
        run: |
          CONTAINER=${{ steps.extract.outputs.container }}
          if [ "$CONTAINER" = "postgresql" ]; then
            MATRIX=$(cat <<'EOF'
          [
            {
              "version": "13.22",
              "postgresql_version": "13.22",
              "citus_version": "11.3.1",
              "patroni_version": "v3.0.2"
            }
          ]
          EOF
          )
            CONTEXT="docker/postgresql"
          elif [ "$CONTAINER" = "wordpress" ]; then
            MATRIX='[{"version": "latest"}]'
            CONTEXT="docker/wordpress/apache"
          else
            MATRIX='[{"version": "latest"}]'
            CONTEXT="docker/$CONTAINER"
          fi
          echo "matrix=$(echo $MATRIX | jq -c .)" >> $GITHUB_OUTPUT
          echo "context=$CONTEXT" >> $GITHUB_OUTPUT

  build:
    needs: setup
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ needs.setup.outputs.context }}
          push: true
          build-args: |
            ${{ matrix.postgresql_version && format('POSTGRESQL_VERSION={0}', matrix.postgresql_version) || '' }}
            ${{ matrix.citus_version && format('CITUS_VERSION={0}', matrix.citus_version) || '' }}
            ${{ matrix.patroni_version && format('PATRONI_VERSION={0}', matrix.patroni_version) || '' }}
          tags: ghcr.io/${{ github.repository_owner }}/containers/${{ needs.setup.outputs.container }}:${{ matrix.version }}-${{ needs.setup.outputs.revision }}
          cache-from: type=gha
          cache-to: type=gha,mode=max